name: Trading Bot Workflow
# Define the schedule using cron syntax
# This example runs every 6 hours
on:
  schedule:
    - cron: '0 */6 * * *'  # minute hour day-month month day-week
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: '3.10'
          activate-environment: trading-env
      
      - name: Install dependencies with conda
        shell: bash -l {0}
        run: |
          conda install -c conda-forge ta-lib numpy pandas scipy matplotlib scikit-learn
          python -m pip install --upgrade pip
          # Install all required packages from the import list
          pip install yfinance alpha_vantage schedule requests pytz beautifulsoup4 holidays
          # These packages are part of the standard library: os, time, json, datetime, threading, re
          
      - name: Verify TA-Lib installation
        shell: bash -l {0}
        run: |
          python -c "import talib; print('TA-Lib successfully installed')"
          
      - name: Run trading bot
        shell: bash -l {0}
        run: python tradingbot.py
        env:
          # Add any environment variables your bot needs
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          
      - name: Save trading data
        uses: actions/upload-artifact@v4
        with:
          name: trading-data
          path: |
            data/
            logs/
          retention-days: 7
