name: Trading Bot Workflow
# Define the schedule using cron syntax
# This example runs every 6 hours
on:
  schedule:
    - cron: '0 */6 * * *'  # Fixed cron syntax: minute hour day-month month day-week
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install TA-Lib C library
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install
          cd ..
          
      - name: Set TA-Lib environment variables
        run: |
          echo "LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy  # Install numpy first as it's often a prerequisite
          pip install --no-binary :all: ta-lib  # Force compilation against the installed C library
          pip install -r requirements.txt
          
      - name: Run trading bot
        run: python tradingbot.py
        env:
          # Add any environment variables your bot needs
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          
      - name: Save trading data
        uses: actions/upload-artifact@v4
        with:
          name: trading-data
          path: |
            data/
            logs/
          retention-days: 7
