name: Trading Bot Workflow

on:
  schedule:
    - cron: '0 3 * * *' # Run daily at 03:00 UTC (08:30 IST)
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install TA-Lib C library
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install
          cd ..

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy matplotlib scikit-learn yfinance alpha_vantage TA-Lib==0.4.24 schedule ccxt python-dotenv requests tensorflow torch pytz plotly ratelimit dash

      - name: Run trading bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python trading_bot.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: trading-bot-logs
          path: ./logs/trading_bot.log

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trading-bot-reports
          path: ./recommendations/*.md
